// ---
// Generate reference safety config files for interactive Claude Code sessions
// ---

import { existsSync, mkdirSync, writeFileSync, chmodSync } from "node:fs";
import { join } from "node:path";
import { SAFE_MODE_ALLOWED, SAFE_MODE_DENIED } from "./permissionArgs.js";

const SETTINGS_FILENAME = "settings.safe-mode-reference.json";
const HOOK_FILENAME = "repo-jail.sh";

function buildSettingsJson(): string {
  const settings = {
    permissions: {
      allow: SAFE_MODE_ALLOWED,
      deny: SAFE_MODE_DENIED,
    },
  };
  return JSON.stringify(settings, null, 2) + "\n";
}

function buildRepoJailHook(): string {
  return `#!/usr/bin/env bash
# repo-jail.sh — blocks file operations outside the git repository root.
# Generated by: trellis-exec init-safety
# Install as a PreToolUse hook on Read|Write|Edit in .claude/settings.json.

set -euo pipefail

# Read tool input JSON from stdin
INPUT=$(cat)

# Extract file_path from tool_input
FILE_PATH=$(echo "$INPUT" | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"file_path"[[:space:]]*:[[:space:]]*"\\(.*\\)"/\\1/')

if [ -z "$FILE_PATH" ]; then
  # No file_path in input — allow (not a file operation)
  exit 0
fi

# Resolve to absolute path
RESOLVED=$(realpath -m "$FILE_PATH" 2>/dev/null || echo "$FILE_PATH")

# Get repo root
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
if [ -z "$REPO_ROOT" ]; then
  # Not in a git repo — allow
  exit 0
fi

# Check if resolved path is under repo root
case "$RESOLVED" in
  "$REPO_ROOT"/*)
    exit 0
    ;;
  "$REPO_ROOT")
    exit 0
    ;;
  *)
    # Block: path is outside repo
    echo '{"reason":"File path is outside the repository root. Blocked by repo-jail hook."}'
    exit 2
    ;;
esac
`;
}

export function scaffoldSafety(projectRoot: string): void {
  const claudeDir = join(projectRoot, ".claude");
  const hooksDir = join(claudeDir, "hooks");

  // Create directories
  if (!existsSync(claudeDir)) {
    mkdirSync(claudeDir, { recursive: true });
  }
  if (!existsSync(hooksDir)) {
    mkdirSync(hooksDir, { recursive: true });
  }

  // Write settings reference
  const settingsPath = join(claudeDir, SETTINGS_FILENAME);
  if (existsSync(settingsPath)) {
    console.log(`Skipping ${settingsPath} (already exists)`);
  } else {
    writeFileSync(settingsPath, buildSettingsJson());
    console.log(`Created ${settingsPath}`);
  }

  // Write repo-jail hook
  const hookPath = join(hooksDir, HOOK_FILENAME);
  if (existsSync(hookPath)) {
    console.log(`Skipping ${hookPath} (already exists)`);
  } else {
    writeFileSync(hookPath, buildRepoJailHook());
    chmodSync(hookPath, 0o755);
    console.log(`Created ${hookPath}`);
  }

  console.log(
    "\nThese files are for interactive Claude Code sessions.\n" +
    "trellis-exec applies its own permissions via CLI flags automatically.\n" +
    "To use these in interactive sessions:\n" +
    `  1. Copy the allow/deny lists from ${SETTINGS_FILENAME} into your .claude/settings.json\n` +
    `  2. Add a PreToolUse hook pointing to ${HOOK_FILENAME} for Read|Write|Edit`,
  );
}
